# Generated by Django 3.1 on 2020-09-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20200901_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='like',
        ),
    ]
