# Generated by Django 3.1 on 2020-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20200902_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='portion',
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='portion',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='portion'),
        ),
    ]
