# Generated by Django 3.1 on 2020-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20200902_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfood',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
