# Generated by Django 3.1 on 2020-09-01 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='userappearance',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='userappearance',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='userappearance',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='userappearance',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='weight'),
        ),
    ]
